# -*- coding: utf-8 -*-
"""calculate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1qAJfsIxZUo9IJdBDBF76JGy-WNG85ws6
"""
#comment
def operation_plus(a,b):
  return a+b

def operation_minus(a,b):
  return a-b

def operation_proizv(a,b):
  return a*b

def operation_delenie(a,b):
  return a/b

def operation_stepen(a,b):
  return a**b

print('Ноль завершит работу программы')
while True:
  oper = input('Введите знак операции:')
  if oper == '0':break
  if oper in ('+','-','*','/','**'):
    x = float(input('Введите 1-е число х = '))
    y = float(input('Введите 2-е число y = '))
  if oper == '+':
    print('Сумма = %.2f' % operation_plus(x,y))
  elif oper == '-':
    print('Разность = %.2f' % operation_minus(x,y))
  elif oper == '*':
    print('Произведение = %.2f' % operation_proizv(x,y))
  elif oper == '/':
    if y != 0:
      print('Деление = %.2f' % operation_delenie(x,y))
    else:
      print('Деление на ноль. Операция невозможна.')
  elif oper == '**':
    print('Степень = %.2f' % operation_stepen(x,y))
  else:
    print('Вы ввели неверный знак операции')
